### ISSUE TITLE
[Home] 레이아웃 구성 및 배너 컴포넌트

### ISSUE THREAD

**Issue by blan19** [GoGo-tm/GoGo_Client#1]
# Description
홈 화면 레이아웃을 잡고 배너 컴포넌트를 구현할 예정입니다

# To-Do
- [x] 홈 레이아웃
- [ ] 배너 컴포넌트 구현
- [ ] 사용자 위치 정보 / 날씨 정보 쿠키 저장
- [x] NavBar 디테일 수정

# Etc..
기타 사항

**Comment by blan19** [comment]
이슈 템플릿 통일을 위해 클로즈했습니다
